name: build and test
on: [push]
jobs:
  just_test:
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - name: go test
      run: go test -v ./...
  test_build_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - name: Get the version
      id: get_tag
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: go test
      run: go test -v ./...
    - name: build
      shell: bash
      run: |
        # Make an artifacts directory
        mkdir -p artifacts
        
        # run the build for each supported OS
        for os in linux darwin windows; do
          CGO_ENABLED=0 GOOS=$os go build -a -ldflags "-X main.version=${{ steps.get_tag.outputs.SOURCE_TAG }}" -o artifacts/chat_$os
        done
        # Windows is a special case for naming
        mv artifacts/chat_windows artifacts/chat_windows.exe
        
        # Check the version prints correct.
        # This is for testing only. Don't use in other work flows.
        cp artifacts/chat_linux .
        chmod 700 chat_linux
        ./chat_linux -v
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
        body_path: .github/workflows/release_body.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
